"""Shared safe HTTP projection for generated speech."""

from fastapi import HTTPException, status
from fastapi.responses import Response

from app.services.ai.exceptions import (
    AIAuthenticationError,
    AIConfigurationError,
    AIConnectionError,
    AIInvalidResponseError,
    AIProviderError,
    AIProviderUnavailableError,
    AIQuotaExceededError,
    AIRateLimitError,
    AITimeoutError,
)
from app.services.ai.provider import SpeechResult


def speech_http_error(exc: Exception) -> HTTPException:
    """Map provider-neutral speech errors to stable safe API responses."""
    if isinstance(exc, AIConfigurationError):
        status_code, code, message = (
            status.HTTP_503_SERVICE_UNAVAILABLE,
            "speech_configuration_invalid",
            "Speech generation is not configured.",
        )
    elif isinstance(exc, (AIRateLimitError, AIQuotaExceededError)):
        status_code, code, message = (
            status.HTTP_429_TOO_MANY_REQUESTS,
            "speech_rate_limited",
            "Speech generation is temporarily unavailable.",
        )
    elif isinstance(exc, AITimeoutError):
        status_code, code, message = (
            status.HTTP_504_GATEWAY_TIMEOUT,
            "speech_timeout",
            "The speech request timed out.",
        )
    elif isinstance(
        exc,
        (AIAuthenticationError, AIConnectionError, AIProviderUnavailableError),
    ):
        status_code, code, message = (
            status.HTTP_503_SERVICE_UNAVAILABLE,
            "speech_provider_unavailable",
            "Speech generation is temporarily unavailable.",
        )
    elif isinstance(exc, (AIInvalidResponseError, AIProviderError, ValueError)):
        status_code, code, message = (
            status.HTTP_502_BAD_GATEWAY,
            "speech_generation_failed",
            "Speech could not be generated. Please try again.",
        )
    else:
        status_code, code, message = (
            status.HTTP_503_SERVICE_UNAVAILABLE,
            "speech_provider_unavailable",
            "Speech generation is temporarily unavailable.",
        )
    return HTTPException(
        status_code=status_code,
        detail={"code": code, "message": message},
    )


def speech_audio_response(result: SpeechResult, *, filename_stem: str) -> Response:
    """Return raw generated bytes with only safe format metadata."""
    return Response(
        content=result.content,
        media_type=result.media_type,
        headers={
            "Content-Disposition": (
                f'inline; filename="{filename_stem}.{result.file_extension}"'
            )
        },
    )
